# Generated by Django 5.1.15 on 2026-09-30 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
                'db_table': 'scheduling_especialidad',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('registro_profesional', models.CharField(blank=True, max_length=60, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='tenants.clinica')),
                ('especialidades', models.ManyToManyField(blank=True, related_name='medicos', to='scheduling.especialidad')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'db_table': 'scheduling_medico',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades', to='tenants.consultorio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='tenants.sucursal')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='scheduling.medico')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
                'db_table': 'scheduling_disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='scheduling.medico')),
            ],
            options={
                'verbose_name': 'bloqueo de agenda',
                'verbose_name_plural': 'bloqueos de agenda',
                'db_table': 'scheduling_bloqueoagenda',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='tenants.clinica')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'scheduling_paciente',
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('notas_evolucion', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='scheduling.paciente')),
            ],
            options={
                'verbose_name': 'ficha clínica',
                'verbose_name_plural': 'fichas clínicas',
                'db_table': 'scheduling_fichaclinica',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('RESCHEDULED', 'Reagendada'), ('CANCELLED', 'Cancelada'), ('ATTENDED', 'Atendida'), ('NO_SHOW', 'No asistió')], default='PENDING', max_length=20)),
                ('origen', models.CharField(default='web', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='tenants.clinica')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='tenants.consultorio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='tenants.sucursal')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='scheduling.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='scheduling.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='scheduling.paciente')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'scheduling_cita',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=80)),
                ('entidad_id', models.CharField(blank=True, max_length=64, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='tenants.clinica')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoría',
                'verbose_name_plural': 'auditorías',
                'db_table': 'scheduling_auditoria',
                'indexes': [models.Index(fields=['clinica', 'created_at'], name='scheduling__clinica_40e846_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['clinica'], name='scheduling__clinica_f976e9_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['medico', 'sucursal'], name='scheduling__medico__7142e3_idx'),
        ),
        migrations.AddIndex(
            model_name='bloqueoagenda',
            index=models.Index(fields=['medico', 'fecha_desde'], name='scheduling__medico__c28453_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinica'], name='scheduling__clinica_debc02_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['clinica', 'fecha'], name='scheduling__clinica_e0b14a_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha'], name='scheduling__medico__f34cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='scheduling__pacient_631036_idx'),
        ),
    ]
