# Generated by Django 5.1.15 on 2026-09-30 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], max_length=20)),
                ('estado', models.CharField(default='pending', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='scheduling.cita')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notifications_notificacion',
                'indexes': [models.Index(fields=['cita'], name='notificatio_cita_id_538801_idx')],
            },
        ),
    ]
